export const INDIA_STATES = [
  "Andaman and Nicobar Islands",
  "Arunachal Pradesh",
  "Assam",
  "Bihar",
  "Chandigarh",
  "Chhattisgarh",
  "Dadra and Nagar Haveli and Daman and Diu",
  "Andhra Pradesh",
  "Delhi",
  "Goa",
  "Gujarat",
  "Haryana",
  "Himachal Pradesh",
  "Jammu and Kashmir",
  "Jharkhand",
  "Karnataka",
  "Kerala",
  "Ladakh",
  "Lakshadweep",
  "Madhya Pradesh",
  "Maharashtra",
  "Manipur",
  "Meghalaya",
  "Mizoram",
  "Nagaland",
  "Odisha",
  "Puducherry",
  "Punjab",
  "Rajasthan",
  "Sikkim",
  "Tamil Nadu",
  "Telangana",
  "Tripura",
  "Uttarakhand",
  "Uttar Pradesh",
  "West Bengal"
] as const;

export const CITIES_BY_STATE: Record<string, string[]> = {
  "Andaman and Nicobar Islands": ["Port Blair", "Diglipur", "Mayabunder", "Rangat"],
  "Arunachal Pradesh": ["Itanagar", "Naharlagun", "Pasighat", "Tawang"],
  "Assam": ["Guwahati", "Dibrugarh", "Silchar", "Jorhat", "Nagaon"],
  "Bihar": ["Patna", "Gaya", "Muzaffarpur", "Bhagalpur", "Darbhanga"],
  "Chandigarh": ["Chandigarh"],
  "Chhattisgarh": ["Raipur", "Bhilai", "Bilaspur", "Korba", "Durg"],
  "Dadra and Nagar Haveli and Daman and Diu": ["Daman", "Diu", "Silvassa"],
  "Andhra Pradesh": ["Visakhapatnam", "Vijayawada", "Guntur", "Nellore", "Kurnool", "Rajahmundry", "Tirupati"],
  "Delhi": ["New Delhi", "Dwarka", "Rohini", "Saket", "Karol Bagh", "Laxmi Nagar"],
  "Goa": ["Panaji", "Margao", "Vasco da Gama", "Mapusa", "Ponda"],
  "Gujarat": ["Ahmedabad", "Surat", "Vadodara", "Rajkot", "Bhavnagar", "Jamnagar", "Gandhinagar"],
  "Haryana": ["Gurugram", "Faridabad", "Panipat", "Ambala", "Hisar", "Karnal"],
  "Himachal Pradesh": ["Shimla", "Dharamshala", "Solan", "Mandi", "Kullu"],
  "Jammu and Kashmir": ["Srinagar", "Jammu", "Anantnag", "Baramulla"],
  "Jharkhand": ["Ranchi", "Jamshedpur", "Dhanbad", "Bokaro", "Hazaribagh"],
  "Karnataka": ["Bengaluru", "Mysuru", "Mangaluru", "Hubballi", "Belagavi", "Ballari", "Davanagere"],
  "Kerala": ["Thiruvananthapuram", "Kochi", "Kozhikode", "Thrissur", "Kollam", "Kannur"],
  "Ladakh": ["Leh", "Kargil"],
  "Lakshadweep": ["Kavaratti", "Agatti", "Amini"],
  "Madhya Pradesh": ["Bhopal", "Indore", "Gwalior", "Jabalpur", "Ujjain", "Sagar"],
  "Maharashtra": ["Ahilyanagar (Ahmednagar)", "Akola", "Amravati", "Chhatrapati Sambhajinagar (Aurangabad)", "Beed", "Bhandara", "Buldhana", "Chandrapur", "Dharashiv (Osmanabad)", "Dhule", "Gadchiroli", "Gondia", "Hingoli", "Jalgaon", "Jalna", "Kolhapur", "Latur", "Mumbai City", "Mumbai Suburban", "Nagpur", "Nanded", "Nandurbar", "Nashik", "Palghar", "Parbhani", "Pune", "Raigad", "Ratnagiri", "Sangli", "Satara", "Sindhudurg", "Solapur", "Thane", "Wardha", "Washim", "Yavatmal", "Achalpur", "Aheri", "Ahilyanagar", "Airoli", "Ajra", "Akkalkot", "Akkurdi", "Akot", "Alibag", "Amalner", "Ambad", "Ambajogai", "Ambarnath", "Ambejogai", "Amgaon", "Amravati Camp", "Anjangaon Surji", "Arjuni Morgaon", "Arni", "Arvi", "Ashti", "Ashti (Beed)", "Atpadi", "Aurad Shahajani", "Ausa", "Badlapur", "Balapur", "Ballarpur", "Baramati", "Barshi", "Basmat", "Basmath", "Belapur", "Bhadgaon", "Bhadravati", "Bhandup", "Bhayandar", "Bhiwandi", "Bhokar", "Bhokardan", "Bhor", "Bhosari", "Bhusawal", "Biloli", "Boisar", "Brahmapuri", "Buldana", "Butibori", "Chakan", "Chalisgaon", "Chandgad", "Chandrapur MIDC", "Chandur", "Chandur Bazar", "Charholi", "Chembur", "Chikhli", "Chimur", "Chinchwad", "Chiplun", "Dahanu", "Dapoli", "Darwha", "Daryapur", "Daund", "Deglur", "Dehu", "Deolali", "Deoli", "Deulgaon Raja", "Dharangaon", "Dharashiv", "Dharni", "Digras", "Dindori", "Dombivli", "Erandol", "Faizpur", "Gadhinglaj", "Gangakhed", "Gangapur", "Georai", "Ghansawangi", "Ghatanji", "Gondpipri", "Goregaon", "Hadapsar", "Hinganghat", "Hinjawadi", "Ichalkaranji", "Igatpuri", "Indapur", "Islampur", "Jaisingpur", "Jamkhed", "Jamner", "Jath", "Jejuri", "Jintur", "Junnar", "Kagal", "Kaij", "Kalamb", "Kalamnuri", "Kalyan", "Kamptee", "Kandhar", "Kannad", "Karad", "Karanja", "Karjat", "Karjat (Raigad)", "Karmala", "Katol", "Kavathe Mahankal", "Khed", "Khopoli", "Kinwat", "Kolad", "Kopargaon", "Koregaon", "Kudal", "Kurduwadi", "Kurla", "Lanja", "Lasalgaon", "Latur MIDC", "Lohara", "Lonavala", "Lonar", "Madha", "Mahabaleshwar", "Mahad", "Majalgaon", "Malegaon", "Malkapur", "Malshiras", "Malvan", "Manchar", "Mangaon", "Mangrulpir", "Manmad", "Manora", "Matheran", "Mehkar", "Mira Road", "Mira Bhayandar", "Mohadi", "Mohol", "Morshi", "Motala", "Muktainagar", "Mul", "Mulund", "Murbad", "Murgud", "Murtijapur", "Murud", "Nagbhid", "Nalasopara", "Nandgaon", "Narkhed", "Narayangaon", "Navi Mumbai", "Neral", "Nevasa", "Nilanga", "Niphad", "Ojhar", "Omerga", "Osmanabad", "Pachora", "Paithan", "Palus", "Pandharpur", "Panvel", "Paranda", "Parli", "Parli Vaijnath", "Partur", "Pathardi", "Pathri", "Patur", "Pauni", "Pen", "Phaltan", "Pimpri", "Pimpri Chinchwad", "Pusad", "Rahata", "Rahuri", "Rajapur", "Rajgurunagar", "Rajura", "Ralegaon", "Ramtek", "Ranjangaon", "Raver", "Risod", "Sailu", "Sakoli", "Sakri", "Sangamner", "Sangola", "Saswad", "Satpur", "Sawantwadi", "Selu", "Shahada", "Shegaon", "Shendurjana", "Shikrapur", "Shirdi", "Shirpur", "Shirur", "Shirwal", "Shrigonda", "Shrirampur", "Sillod", "Sinnar", "Sironcha", "Solapur MIDC", "Sonai", "Tasgaon", "Telhara", "Tembhurni", "Thakurli", "Tirora", "Tuljapur", "Tumsar", "Udgir", "Ulhasnagar", "Umarga", "Umarkhed", "Umred", "Uran", "Uruli Kanchan", "Vaijapur", "Vasai", "Vashi", "Vita", "Wadgaon", "Wagholi", "Wai", "Waluj", "Wani", "Warora", "Warud", "Washim MIDC", "Yawal", "Yeola", "Yevla"],
  "Manipur": ["Imphal", "Thoubal", "Bishnupur", "Churachandpur"],
  "Meghalaya": ["Shillong", "Tura", "Jowai", "Nongstoin"],
  "Mizoram": ["Aizawl", "Lunglei", "Champhai", "Kolasib"],
  "Nagaland": ["Kohima", "Dimapur", "Mokokchung", "Tuensang"],
  "Odisha": ["Bhubaneswar", "Cuttack", "Rourkela", "Sambalpur", "Puri", "Berhampur"],
  "Puducherry": ["Puducherry", "Karaikal", "Mahe", "Yanam"],
  "Punjab": ["Ludhiana", "Amritsar", "Jalandhar", "Patiala", "Bathinda", "Mohali"],
  "Rajasthan": ["Jaipur", "Udaipur", "Jodhpur", "Kota", "Ajmer", "Bikaner", "Alwar"],
  "Sikkim": ["Gangtok", "Namchi", "Gyalshing", "Mangan"],
  "Tamil Nadu": ["Chennai", "Coimbatore", "Madurai", "Salem", "Tiruchirappalli", "Erode", "Tirunelveli"],
  "Telangana": ["Hyderabad", "Warangal", "Nizamabad", "Karimnagar", "Khammam", "Mahbubnagar"],
  "Tripura": ["Agartala", "Udaipur", "Dharmanagar", "Kailashahar"],
  "Uttarakhand": ["Dehradun", "Haridwar", "Haldwani", "Roorkee", "Rudrapur"],
  "Uttar Pradesh": ["Lucknow", "Kanpur", "Noida", "Ghaziabad", "Varanasi", "Prayagraj", "Agra", "Meerut", "Gorakhpur"],
  "West Bengal": ["Kolkata", "Howrah", "Siliguri", "Durgapur", "Asansol", "Kharagpur"]
};
